---
- name: Prod Environment Playbook
  hosts: Prod
  tasks:
  - name: Deployment of Medicure Application to Prod Environment
    ansible.builtin.shell: docker run -itd -p 8086:8082 rajasghyd/medicure:1.1
