---
- name: Test Environment Playbook
  hosts: Test
  tasks:
  - name: Deployment of Medicure Application to Test Environment
    ansible.builtin.shell: docker run -itd -p 8085:8082 rajasghyd/medicure:1.1
